# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config.json

version: "1"

global:
  prevent-sleep: true
  command-output: auto
  log: /home/wolf/resticprofile.log
  default-command: snapshots
  ionice-class: 2
  min-memory: 100
  priority: normal
  restic-arguments-filter: true
  scheduler: auto
  initialize: true

base:
  password-file: /run/secrets/other/restic/password
  backup:
    base-dir: /home/wolf
    exclude:
      - .direnv
      - .cache
      - node_modules
      - .cargo
      - .rustup
      - .local/share/Trash
      - .local/share/Steam/.*

laptop:
  repository: /mnt/vault/Restic/Laptop
  lock: /tmp/resticprofile-laptop.lock
  inherit: base
  retention:
    keep-hourly: 1
    keep-daily: 30
    keep-weekly: 26
    keep-monthly: unlimited
    keep-yearly: unlimited
  backup:
    source:
      - .
    exclude-file:
      - Obsidian

obsidian:
  repository: /mnt/vault/Restic/Obsidian
  lock: /tmp/resticprofile-obsidian.lock
  inherit: base
  retention:
    keep-hourly: 3
    keep-daily: 30
    keep-weekly: "unlimited"
    keep-monthly: "unlimited"
    keep-yearly: "unlimited"
  backup:
    schedule:
      - "0 23 * * *"
    source:
      - /home/wolf/Obsidian
