# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config-2.json

version: "2"

global:
  prevent-sleep: true
  command-output: auto
  log: /home/wolf/resticprofile.log
  default-command: snapshots
  ionice-class: 2
  min-memory: 100
  priority: normal
  restic-arguments-filter: true
  scheduler: auto
  initialize: true

profiles:
  base:
    password-file: /run/secrets/other/restic/password
    verbose: 2
    backup:
      exclude-caches: true
    run-before:
      - export access_key_id={{S3_ACCESS_KEY_ID}}
      - export secret_access_key={{S3_SECRET_ACCESS_KEY}}
      - export endpoint={{S3_ENDPOINT}}

  laptop:
    repository: local:/mnt/vault/Restic/Laptop
    lock: /tmp/resticprofile-laptop.lock
    inherit: base
    retention:
      keep-hourly: 1
      keep-daily: 30
      keep-weekly: 26
      keep-monthly: 9999
      keep-yearly: 9999
    backup:
      source:
        - /home/wolf
      exclude:
        - /**/.direnv
        - /**/.cache
        - /**/node_modules
        - /**/.local/share/Trash
        - /**/.local/share/Steam/.*
        - /home/wolf/Obsidian/**

  obsidian:
    repository: local:/mnt/vault/Restic/Obsidian
    lock: /tmp/resticprofile-obsidian.lock
    inherit: base
    environment:
      AWS_ACCESS_KEY_ID: ${access_key_id}
      AWS_SECRET_ACCESS_KEY: ${secret_access_key}
    retention:
      keep-hourly: 3
      keep-daily: 30
      keep-weekly: 9999
      keep-monthly: 9999
      keep-yearly: 9999
    backup:
      source:
        - /home/wolf/Obsidian
      exclude:
        - /**/.direnv
        - /**/.cache
        - /**/node_modules
    schedule:
      - "0 23 * * *"
